### ISSUE TITLE
Is the Numpyro example still relevant?

### ISSUE THREAD

**Issue by mvsoom** [Joshuaalbert/jaxns#142]
See https://num.pyro.ai/en/latest/examples/gaussian_shells.html. It doesn't work with latest numpyro/jaxns versions due to refactoring of jaxns. Is this intended to work? Cheers

**Comment by Joshuaalbert** [comment]
I'll take a look at the numpyro interface and fix it. It would work if the interface works. What's the error message?

**Comment by mvsoom** [comment]
Some "outdated" symbols cannot be imported from jaxns as they have been renamed etc. It is easy to fix in the source code by commenting it out, but then more fundamental things start to be missing, and without properly understanding jaxns source code, I gave up. But anyway, I am just using jaxns' PPL, and find it very convenient, so feel free to close this issue. Thanks for the excellent library.

**Comment by Joshuaalbert** [comment]
Glad that you're liking the probabilistic programming framework of JAXNS. Always glad to have feedback too. For numpyro update, @fehiepsi do you want me to do that?

**Comment by fehiepsi** [comment]
I think it is fixed [in this PR](https://github.com/pyro-ppl/numpyro/pull/1738). Because jaxns changes apis in each release, we typically pin the jaxns version in each release. Anyway, I'm happy to merge PRs that fix jaxns issues.

**Comment by Joshuaalbert** [comment]
Thanks @fehiepsi and fyi API should be fairly stable now.
