### ISSUE TITLE
Enable jaxns's readthedocs

### ISSUE THREAD

**Issue by fehiepsi** [Joshuaalbert/jaxns#26]
It would be nice to have readthedocs for jaxns, so we can link to the original documentation of jaxns' functionalities through inter sphinx functionality. :)

**Comment by Joshuaalbert** [comment]
I don't have the capacity to do this. Any volunteers would be welcome to help set this up. Really great idea!

**Comment by alexlyttle** [comment]
I've been using `jaxns` via `numpyro` a fair bit in my own work and would be happy to have a go at making documentation having done it previously on a few projects. I can get started in a week once back from holiday, but wanted to give a heads-up!

**Comment by Joshuaalbert** [comment]
Hi @alexlyttle I'd love that. You'd officially be the first external contributor, and that's awesome. How can I help to get you started?

**Comment by alexlyttle** [comment]
Awesome! I have put together something on the [`docs` branch](https://github.com/alexlyttle/jaxns/tree/docs) of my own fork and published live on readthedocs [here](https://jaxns.readthedocs.io/en/latest/api/jaxns/index.html) if you'd like to take a look. I have added a warning in case anyone stumbles across the docs that it is a work in progress and not yet associated with the official codebase. I will make a pull request soon too, just wanted to get your initial thoughts on the overall structure of the docs?

I am using `sphinx` to compile the documentation. To keep it easy to maintain, the API documentation is generated automatically with [SphinxAutoAPI](https://sphinx-autoapi.readthedocs.io/en/latest/).

There will be some work to do cleaning up the docstrings to make them easily read by `sphinx` (writing them consistently in the Google docstring style works well).

**Comment by Joshuaalbert** [comment]
Looks great! I will make it a point to unify docstrings in terms of Google structure in my IDE. Anything else that would make things better on my side? For example is there a way to write latex that will render in the docstrings?

**Comment by alexlyttle** [comment]
Sounds good! I'll make a pull request soon.

You can render math, here's an example extract from a docstring,

```
For inline maths, :math:`f(x) = a + b \log(x)`.

For displayed maths,

.. math::

    f(x) = a + b \log(x)
```

see [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#math) for more examples.

**Comment by Joshuaalbert** [comment]
Done with #66
