### ISSUE TITLE
Bayesian neural network example

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/jaxns#37]
The long-awaited evidence calculation of a neural network model.

**Comment by mvsoom** [comment]
Hi Joshua, this might be of interest: https://arxiv.org/abs/2004.12211.

**Comment by Joshuaalbert** [comment]
Thanks for the link. Sad to see I was the first to publish an analysis of Bayesian evidence for neural networks. Alas, can't do it all.

**Comment by mvsoom** [comment]
But you can do it better :)

**Comment by Joshuaalbert** [comment]
Example added.
