### ISSUE TITLE
Corner plot is slow for large samples

### ISSUE THREAD

**Issue by fehiepsi** [Joshuaalbert/jaxns#4]
While running an example at [this PR](https://github.com/pyro-ppl/numpyro/pull/807/files), I observed that `corner` plot is pretty slow for the result with 8 variables and 65854 "weighted" samples. I am not sure if this slowness is expected.

Btw, I think it is unnecessary to use JAX in plotting utility because outside of JIT, JAX functions are slower and less coverage than numpy.

(`seaborn` has a nice function [pairplot](https://seaborn.pydata.org/generated/seaborn.pairplot.html) for this corner plot, which is much faster)

**Comment by Joshuaalbert** [comment]
I fixed #3. Can you see if this is solved? I think resampling was the reason.

**Comment by fehiepsi** [comment]
Cool! It is much faster now. Thanks, @Joshuaalbert!
