### ISSUE TITLE
Typo `stoachastic_uncertainty`

### ISSUE THREAD

**Issue by fehiepsi** [Joshuaalbert/jaxns#5]
I guess the argument [stoachastic_uncertainty](https://github.com/Joshuaalbert/jaxns/blob/master/jaxns/nested_sampling.py#L297) is a typo and it should be `stochastic_uncertainty`?

**Comment by Joshuaalbert** [comment]
I fixed this in 219d0aa91e6468056f69ccfc1369b97eda2e3872
So I'll close this and the PR, since it's not needed now. But, thanks for making the PR.
