### ISSUE TITLE
Verbose option for when running a NestedSampler instance

### ISSUE THREAD

**Issue by ekerrison** [Joshuaalbert/jaxns#67]
**Is your feature request related to a problem? Please describe.**
I'm trying to work out why a nested sampling model is hanging, and it's hard to know where in the NestedSampler object things are going wrong (but I have at least narrowed the problem down to when I run the nested sampler).

**Describe the solution you'd like**
A verbose option for the NestedSampler that prints out progress while running, to help with debugging. 

**Describe alternatives you've considered**
I haven't tried anything else to do with the NestedSampler object, but I can't find any sort of verbose option in the docs.

**Additional context**
I was previously using a combination of Bilby and Dynesty to do nested sampling, and there was a 'print_progress' option which I found very helpful. For reference it printed out things like: runtime, dlogZ and the total number of likelihood calls made so far

**Comment by Joshuaalbert** [comment]
Good idea! I think this can be incorperated at a granular scale. Certain operations are jit-compiled so we can't get the type of temporal resolution that those cythonic packages have.

**Comment by tomkimpson** [comment]
+1 for this idea. Would it be tricky to implement?

**Comment by Joshuaalbert** [comment]
It's possible to get a very low resolution feedback. For example between approximate nested sampling phase and exact nested sampling phase. To see the output from each shrinkage step would not be possible with JAX. Although perhaps an alternative is to progressively refine the state to higher and higher likelihoods, and print output in between. I will post how to do this later.

**Comment by Joshuaalbert** [comment]
This is looking to be a little too complicated, and would cause performance degradation. I agree it could make it easy to watch the process, but that shouldn't come at the cost of performance. I'll take this off the todo pile. If there are enough voices calling for this, a wrapper could be something I consider.

**Comment by Joshuaalbert** [comment]
@tomkimpson @ekerrison this is now a priority. Should be available in a few days.

**Comment by Joshuaalbert** [comment]
Done. Use `verbose=True` option.

```python
ns = DefaultNestedSampler(
    model=model,
    ...
    verbose=True)
```
