### ISSUE TITLE
Why is the likelihood corrected?

### ISSUE THREAD

**Issue by mvsoom** [Joshuaalbert/jaxns#70]
This is not a bug, but just a question: why is the [log likelihood corrected](https://github.com/Joshuaalbert/jaxns/blob/fac1906506e52fa143a526cace52a6b7055fe617/jaxns/nested_sampler/nested_sampler.py#L127) by the log absdet jacobian of the prior transform?

This correction is necessary for using VI or MAP optimization, but in my understanding should not be applied for likelihood-constrained sampling. For example, Skilling's programs in [Sivia & Skilling (2006)](http://aprsa.villanova.edu/files/sivia.pdf) do not do this (see the lighthouse example). `dynesty` doesn't do this either -- the `ptform()` function is purely for user convenience -- it does not have access to the prior transform Jacobian.

Am I missing something obvious here?

**Comment by Joshuaalbert** [comment]
In nested sampling we reparametrise the prior to typically be the uniform measure and use a quantile to push the uniform samples to the appropriate domain. But sometimes we don't have a quantile. In this case we use another base measure which is taken to be any other distribution with enclosing support of the target prior (the ideal would be to use the posterior for maximal efficiency). However upon performing this reparametrisation we need to adjust the integrand. This correction is the one that is applied. Actually the common jargon in literature is prior repartitioning. There is some attention on repartitioning for another reason, which is to choose the repartitioning to minimize the information gain from repartitioned prior to posterior which in turn means maximal sampling efficiency. CheersJosjOn Dec 21, 2022 12:50, Marnix Van Soom ***@***.***> wrote:
This is not a bug, but just a question: why is the log likelihood corrected by the log absdet jacobian of the prior transform?
This correction is necessary for using VI or MAP optimization, but in my understanding should not be applied for likelihood-constrained sampling. For example, Skilling's programs in Sivia & Skilling (2006) do not do this (see the lighthouse example). dynesty doesn't do this either -- the ptform() function is purely for user convenience -- it does not have access to the prior transform Jacobian.
Am I missing something obvious here?

**Comment by mvsoom** [comment]
OK, thanks for the detailed explanation. Very interesting! I heard about posterior repartitioning before, but the application to missing quantile functions is new to me.
