### ISSUE TITLE
Documentation API Reference sidebar displays each item twice

### ISSUE THREAD

**Issue by alexlyttle** [Joshuaalbert/jaxns#77]
**Describe the bug**
During usage, I have noticed some issues with the documentation.

* The warning message still displays on the home page (needs to be removed)
* The API sidebar menu displays every item twice

**Minimal Verifiable Complete Example**
Go to https://jaxns.readthedocs.io/ and you will see the old warning message (image below). Then, click on "jaxns" under "API Reference" and scroll down. You will notice that items in the menu are duplicated.

**Screenshots**
![Screenshot 2023-01-04 at 09 36 19](https://user-images.githubusercontent.com/43786145/210525811-7d06d532-9a51-47f8-a992-4258f49f7ebf.png)

**Proposed fix**
Removing the warning message is easy, it can be deleted from [docs/index.rst](https://github.com/Joshuaalbert/jaxns/blob/main/docs/index.rst). 

I am happy to investigate the menu issue as it's probably due to the automatic API generation conflicting with something.

**JAXNS version**
2.0

**Comment by Joshuaalbert** [comment]
Seems to be resolved
