### ISSUE TITLE
Question about numpyo

### ISSUE THREAD

**Issue by fountaindive** [Joshuaalbert/jaxns#79]
Hey,

I just tried to use the latest version of jaxns with numpyro and it doesn't seem to work. I think `jaxns.prior_transforms` has been refactored in v2 or something?

Are you planning on updating numpyro to work with jaxns v2?

Thanks!

**Comment by Joshuaalbert** [comment]
This requires the work of Du Phan who maintains that. I will take a look at the code though and see if I can make a pr for it.CheersJoshOn Jan 20, 2023 05:15, Sebastian Khan ***@***.***> wrote:
Hey,
I just tried to use the latest version of jaxns with numpyro and it doesn't seem to work. I think jaxns.prior_transforms has been refactored in v2 or something?
Are you planning on updating numpyro to work with jaxns v2?
Thanks!

**Comment by fountaindive** [comment]
Hi,

Ah OK, I thought you maintained it. Thanks for replying / taking a look. Absolutely no issue if not.

Cheers

**Comment by fehiepsi** [comment]
I took a look but it is quite complicated now given than jaxns is introducing its own ppl. I would suggest to use jaxns ppl for full integration.

**Comment by fountaindive** [comment]
OK thanks very much for the info! Closing this now I guess. All the best!
